/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.abc.CustomerSelfServiceSystem;

import com.abc.CreditCardSelfService.SelfServiceMenu;
import com.abc.JDBCConnection.ConnectionClass;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
//import static javafx.beans.binding.Bindings.select;

/**
 *
 * @author test
 *
 *
 *
 *
 */
public class CreditCardLogin extends javax.swing.JFrame {

    public static int cid;
    public static String topName;

    /**
     * Creates new form CreditCardLogin
     */
    public CreditCardLogin() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUname = new javax.swing.JLabel();
        txtUname = new javax.swing.JTextField();
        lblPswrd = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPswrd = new javax.swing.JPasswordField();
        lblmsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUname.setText("User Name");

        txtUname.setText("cust123");
        txtUname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUnameMouseClicked(evt);
            }
        });
        txtUname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnameActionPerformed(evt);
            }
        });

        lblPswrd.setText("Password");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTitle.setText("Welcome to Credit Card Self-Service System ");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(222, 21, 21));
        jLabel1.setText("*");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 23, 23));
        jLabel2.setText("*");

        txtPswrd.setText("newpass");
        txtPswrd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPswrdKeyReleased(evt);
            }
        });

        lblmsg.setForeground(new java.awt.Color(241, 10, 10));
        lblmsg.setText("                     ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPswrd)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(199, 199, 199)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtPswrd, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                                .addComponent(txtUname))
                                            .addGap(59, 59, 59)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblUname)
                                            .addComponent(btnSubmit))
                                        .addGap(64, 64, 64)
                                        .addComponent(btnClear)
                                        .addGap(4, 4, 4))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(lblmsg)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUname)
                    .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPswrd)
                    .addComponent(jLabel2)
                    .addComponent(txtPswrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmsg)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnClear))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean verification(String usrName, String pass) throws ClassNotFoundException, SQLException {
        try {
            Connection connect = ConnectionClass.getConnected();
            String query = "select custpassword from customer where cust_user_name=?";
            PreparedStatement stmt = connect.prepareStatement(query);
            stmt.setString(1, usrName);
            ResultSet rs = stmt.executeQuery();
            return rs.next() && rs.getString(1).equals(pass);
        } catch (Exception e) {
            return false;
        }

    }


    private void txtUnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnameActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtUname.setText("");
        txtPswrd.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        // int flag = 0;
        String Uname = txtUname.getText();
        String Pswrd = txtPswrd.getText();
        if (Uname.equals("") || Pswrd.equals(""))
            lblmsg.setText("Fields can't be empty");

        else {
            try {
                if (verification(Uname, Pswrd)) {
                    CustomerLoginTo.login = 1;
                    Connection con = ConnectionClass.getConnected();
                    Statement st1 = con.createStatement();

                    //lname+="hai";
                    // obj.setWel("welcome " +topName);
                    Connection connect = ConnectionClass.getConnected();
                    String sql = "select customer_id from customer where cust_user_name='" + Uname + "'";
                    Statement st = connect.createStatement();
                    ResultSet rs = st.executeQuery(sql);
                    while (rs.next()) {
                        cid = rs.getInt(1);
                        BillPaymentLogin.cust_id = rs.getString(1);
                        CustomerLogin.customerid = rs.getInt(1);
                    }

                    String s = "select name from customer where customer_id=" + CreditCardLogin.cid;
                    ResultSet rs1 = st1.executeQuery(s);

                    while (rs1.next()) {
                        topName = rs1.getString(1);

                        BillPaymentLogin.cust_name = rs1.getString(1);
                        CustomerLogin.customername = rs1.getString(1);

                        BillPaymentLogin.cust_name=rs1.getString(1);
                        CustomerLogin.customername=rs1.getString(1);
                    }

                    SelfServiceMenu obj = new SelfServiceMenu(topName);
                    obj.setVisible(true);
                    this.setVisible(false);
                } else {
                    lblmsg.setText("Incorrect user name or password");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                lblmsg.setText("DataBase Not Connected");
                ex.printStackTrace();
            }


    }//GEN-LAST:event_btnSubmitActionPerformed
    }
    private void txtPswrdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPswrdKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String Uname = txtUname.getText();
            String Pswrd = txtPswrd.getText();
            if (Uname.equals("") || Pswrd.equals("")) {
                lblmsg.setText("Fields cannot be empty");
            } else {
                try {
                    if (verification(Uname, Pswrd)) {
                        lblmsg.setText("Loging in..");
                        SelfServiceMenu obj;
                        obj = new SelfServiceMenu(topName);
                        obj.setVisible(true);
                        this.setVisible(false);
                    } else {
                        lblmsg.setText("Incorrect user name or password");
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    lblmsg.setText("DataBase Not Connected");
                }
            }

        }

    }//GEN-LAST:event_txtPswrdKeyReleased
    boolean only_once = true;
    private void txtUnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUnameMouseClicked
        // TODO add your handling code here:
        if (only_once) {
            txtUname.setText("");
            only_once = false;
    }//GEN-LAST:event_txtUnameMouseClicked
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditCardLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditCardLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditCardLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditCardLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditCardLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPswrd;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUname;
    private javax.swing.JLabel lblmsg;
    private javax.swing.JPasswordField txtPswrd;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
