/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.abc.CustomerSelfServiceSystem;

import com.abc.JDBCConnection.ConnectionClass;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author shivasai
 */
public class CustomerLogin extends javax.swing.JFrame {

    public static  int customerid;
    public static String customername;

    /**
     * Creates new form Login
     */
    public CustomerLogin() {
        initComponents();
        clearBtn.setToolTipText("Clear fields");
        errlbl.setForeground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header1 = new javax.swing.JLabel();
        userNamelbl = new javax.swing.JLabel();
        passWordlbl = new javax.swing.JLabel();
        userNametxt = new javax.swing.JTextField();
        passWordtxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        errlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");

        header1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        header1.setText("Welcome to Customer Self-service System");

        userNamelbl.setText("User Name:");

        passWordlbl.setText("Password:");

        userNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNametxtActionPerformed(evt);
            }
        });

        passWordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passWordtxtActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(247, 8, 8));
        jLabel1.setText("*");

        jLabel2.setForeground(new java.awt.Color(244, 15, 15));
        jLabel2.setText("*");

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userNamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passWordlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(submitBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(userNametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                        .addComponent(passWordtxt))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(errlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userNametxt)
                                .addComponent(userNamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passWordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passWordlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(clearBtn))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validation(String userName,String passWord)throws SQLException,ClassNotFoundException
    {
        
    
        try
        {
            Connection con=ConnectionClass.getConnected();
            String query="select custpassword from customer where cust_user_name=?";
            PreparedStatement stmt=con.prepareStatement(query);
            stmt.setString(1,userName);
            ResultSet res=stmt.executeQuery();
           
            return res.next() && res.getString(1).equals(passWord);
        }
        catch(ClassNotFoundException | SQLException e)
                {
                    return false;
                }
    }
    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        userNametxt.setText("");
        passWordtxt.setText("");
        errlbl.setText(null);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed

       String usrName = userNametxt.getText();
        String password = passWordtxt.getText();
        if (usrName.equals("") || password.equals("")) {
            errlbl.setText("Fields cannot be empty");
        } else {
            try {
                if (validation(usrName, password)) {
                    CustomerLoginTo.login=1;
                    CustomerServiceMenu obj;
                    customerid=getCustomerid(usrName);
                    BillPaymentLogin.cust_id=String.valueOf(getCustomerid(usrName));
                    CreditCardLogin.cid=getCustomerid(usrName);
                    customername=getCustomerName(usrName);
                    BillPaymentLogin.cust_name=String.valueOf(getCustomerName(usrName));
                    CreditCardLogin.topName=getCustomerName(usrName);
                    obj = new CustomerServiceMenu();
                    obj.setVisible(true);
                    this.setVisible(false);
                } else {
                    errlbl.setText("Incorrect user name or password");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                errlbl.setText("DataBase Not Connected");
            }
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private int getCustomerid(String userName)throws SQLException,ClassNotFoundException
    {
        int r=0;
        try
        {
            Connection con=ConnectionClass.getConnected();
            String query="select customer_id from customer where cust_user_name=?";
            PreparedStatement stmt=con.prepareStatement(query);
            stmt.setString(1,userName);
            ResultSet res=stmt.executeQuery();
            res.next();
            r=res.getInt(1);
            
        }
        catch(ClassNotFoundException | SQLException e)
                {
                    e.printStackTrace();
                }
        return r;
    }
    private String getCustomerName(String userName)throws SQLException,ClassNotFoundException
    {
        String r="";
        try
        {
            Connection con=ConnectionClass.getConnected();
            String query="select name from customer where cust_user_name=?";
            PreparedStatement stmt=con.prepareStatement(query);
            stmt.setString(1,userName);
            ResultSet res=stmt.executeQuery();
            res.next();
            r=res.getString(1);
            
        }
        catch(ClassNotFoundException | SQLException e)
                {
                    e.printStackTrace();
                }
        return r;
    }
    
    private void userNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNametxtActionPerformed

    private void passWordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passWordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passWordtxtActionPerformed

    /**
     * @param args the command line arguments
     */
   

       
    

   

       

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel errlbl;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel passWordlbl;
    private javax.swing.JPasswordField passWordtxt;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel userNamelbl;
    private javax.swing.JTextField userNametxt;
    // End of variables declaration//GEN-END:variables
}
