/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.abc.CustomerSelfServiceSystem;

import com.abc.JDBCConnection.ConnectionClass;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JSpinner.DefaultEditor;

/**
 *
 * @author test
 */
public class LostStolenCard extends javax.swing.JFrame {

    /**
     * Creates new form LostStolenCard
     */
    public LostStolenCard() {
        initComponents();
        spinDate.setEditor(new JSpinner.DateEditor(spinDate,"dd.MM.yyyy"));
        lblName.setText(CustomerServiceMenu.name);
        Iterator itr=CustomerServiceMenu.acc.iterator();
        while(itr.hasNext())
        {
            String s=(String)itr.next();
            cmbAccountNo.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReportStolenCard = new javax.swing.JLabel();
        lblNamefield = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAccountNo = new javax.swing.JLabel();
        cmbAccountNo = new javax.swing.JComboBox<>();
        lblDate = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        spinDate = new javax.swing.JSpinner();
        lblCard = new javax.swing.JLabel();
        cmbCardNo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOST OR STOLEN CARD");

        lblReportStolenCard.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblReportStolenCard.setText("Report Lost/Stolen Debit Card");

        lblNamefield.setText("Name:");

        lblAccountNo.setText("Account No:");

        cmbAccountNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccountNoActionPerformed(evt);
            }
        });

        lblDate.setText("Date:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblMsg.setForeground(new java.awt.Color(231, 7, 7));

        spinDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));

        lblCard.setText("Card No:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(lblReportStolenCard)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamefield)
                            .addComponent(lblDate))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                        .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnSubmit)
                                .addGap(60, 60, 60)
                                .addComponent(btnBack)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(spinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAccountNo)
                            .addComponent(lblCard))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbAccountNo, 0, 226, Short.MAX_VALUE)
                            .addComponent(cmbCardNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblReportStolenCard)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNamefield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountNo)
                    .addComponent(cmbAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCard)
                    .addComponent(cmbCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(spinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(lblMsg)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAccountNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccountNoActionPerformed
        cmbCardNo.removeAllItems();
        try
       {
            Connection connect=ConnectionClass.getConnected();
            String query="Select card_no from credit_card_detail where account_number=?";
            PreparedStatement stmt=connect.prepareStatement(query);
            stmt.setString(1,(String)cmbAccountNo.getSelectedItem());
            ResultSet rs=stmt.executeQuery();
            while(rs.next())
            {
                cmbCardNo.addItem(rs.getString(1));
            }   
       }
       catch(ClassNotFoundException|SQLException e){
           e.printStackTrace();
       }
    }//GEN-LAST:event_cmbAccountNoActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    ServiceRequest obj=new ServiceRequest();
    obj.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        if(cmbAccountNo.getSelectedIndex()==-1 || cmbCardNo.getSelectedIndex()==-1)
        {
            lblMsg.setText("Enter all the fields");
        }
        else
        {
            
            int flag=0;
            try{
                Connection connect=ConnectionClass.getConnected();
                String query1="select card_no from stolen_lost_card";
                PreparedStatement stmt1=connect.prepareStatement(query1);
                ResultSet rs1=stmt1.executeQuery();
                while(rs1.next())
                {
                    if(Integer.parseInt((String) cmbCardNo.getSelectedItem())==rs1.getInt(1))
                      flag=1;  
                }
            }
            catch(ClassNotFoundException|SQLException e)
            {
                 e.printStackTrace();
            }
            if(flag==1)
            {
                lblMsg.setText("Card Detail Already present");
            }
            else
            {
            try
            {
                Connection connect=ConnectionClass.getConnected();
                String query1="select CSR_ID_SEQ.nextval from dual";
                PreparedStatement stmt1=connect.prepareStatement(query1);
                ResultSet rs1=stmt1.executeQuery();
                rs1.next();
                int r=rs1.getInt(1);
                String query2="insert into customer_service_request (csr_id,csr_type,csr_date,account_number) values("+r+",3,CURRENT_TIMESTAMP,'"+cmbAccountNo.getSelectedItem()+"')";
                PreparedStatement stmt2=connect.prepareStatement(query2);
                int rs2=stmt2.executeUpdate();
                if(rs2>0)
                    JOptionPane.showMessageDialog(null,"Request Added Successfully");
                String query3="insert into stolen_lost_card values(to_date('"+new SimpleDateFormat("yyyy/MM/dd").format(spinDate.getValue())+"','yyyy/MM/dd'),"+r+","+cmbCardNo.getSelectedItem()+")";
                PreparedStatement stmt3=connect.prepareStatement(query3);
                stmt3.executeUpdate();
                
            }
            catch(ClassNotFoundException|SQLException e){
                e.printStackTrace();
            }
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LostStolenCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LostStolenCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LostStolenCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LostStolenCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LostStolenCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbAccountNo;
    private javax.swing.JComboBox<String> cmbCardNo;
    private javax.swing.JLabel lblAccountNo;
    private javax.swing.JLabel lblCard;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNamefield;
    private javax.swing.JLabel lblReportStolenCard;
    private javax.swing.JSpinner spinDate;
    // End of variables declaration//GEN-END:variables
}
