/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.abc.CustomerSelfServiceSystem;

import com.abc.JDBCConnection.ConnectionClass;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

/**
 *
 * @author shivasai
 */
public class MyProfile extends javax.swing.JFrame {

    int id=CustomerLogin.customerid;
    /**
     * Creates new form MyProfile
     */
    public MyProfile()
            {
                        initComponents();
errlbl.setForeground(Color.red);
                 
        try
        {
            
            Connection con=ConnectionClass.getConnected();
            String query="select name,cust_user_name,date_of_birth,mobile_num,address,city,pin,country,pan,email_id from customer where customer_id="+id;
            PreparedStatement stmt=con.prepareStatement(query);
          
            ResultSet s=stmt.executeQuery();
            s.next();
           
           
          wellbl.setText("Welcome  "+s.getString(1));
          
    nametxt.setText(s.getString(1));
    userNametxt.setText(s.getString(2));
    DateFormat dateFormat = new SimpleDateFormat("dd-MM-yy");
     String strDate = dateFormat.format(s.getDate(3));
    DOBtxt.setText(strDate);
    phNotxt.setText(s.getString(4));
    addresstxt.setText(s.getString(5));
    citytxt.setText(s.getString(6));
    if(s.getString(7)==null)
    {
        pinCodetxt.setText("-");
    }
    else
    {
    pinCodetxt.setText(s.getString(7));
    }
    countrytxt.setText(s.getString(8));
    panNotxt.setText(s.getString(9));
    emailtxt.setText(s.getString(10));
            
            
            
        }
        catch(ClassNotFoundException | SQLException e)
                {
                    
                    System.out.println("err");
                }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header3 = new javax.swing.JLabel();
        wellbl = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JLabel();
        userNamelbl = new javax.swing.JLabel();
        userNametxt = new javax.swing.JLabel();
        DOBlbl = new javax.swing.JLabel();
        DOBtxt = new javax.swing.JLabel();
        phNolbl = new javax.swing.JLabel();
        phNotxt = new javax.swing.JLabel();
        Addresslbl = new javax.swing.JLabel();
        citylbl = new javax.swing.JLabel();
        pinCodelbl = new javax.swing.JLabel();
        countrylbl = new javax.swing.JLabel();
        emaillbl = new javax.swing.JLabel();
        citytxt = new javax.swing.JTextField();
        addresstxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        countrytxt = new javax.swing.JTextField();
        pinCodetxt = new javax.swing.JTextField();
        panNolbl = new javax.swing.JLabel();
        panNotxt = new javax.swing.JLabel();
        submitBt = new javax.swing.JButton();
        backBt = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        errlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MY PROFILE");

        header3.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        header3.setText("Profile Details");

        wellbl.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        wellbl.setText("Welcome");

        namelbl.setText("Name");

        nametxt.setText("name");

        userNamelbl.setText("User Name");

        userNametxt.setText("username");

        DOBlbl.setText("DOB");

        DOBtxt.setText("Dob");

        phNolbl.setText("Phone No:");

        phNotxt.setText("phno");

        Addresslbl.setText("Address");

        citylbl.setText("City");

        pinCodelbl.setText("Pin Code");

        countrylbl.setText("Country");

        emaillbl.setText("Email");

        citytxt.setText("city");

        addresstxt.setText("Address");
        addresstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresstxtActionPerformed(evt);
            }
        });

        emailtxt.setText("Email");

        countrytxt.setText("country");

        pinCodetxt.setText("pincode");

        panNolbl.setText("Pan No");

        panNotxt.setText("panno");

        submitBt.setText("Submit");
        submitBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtActionPerformed(evt);
            }
        });

        backBt.setText("Back");
        backBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(247, 8, 8));
        jLabel15.setText("*");

        jLabel16.setForeground(new java.awt.Color(247, 8, 8));
        jLabel16.setText("*");

        jLabel17.setForeground(new java.awt.Color(247, 8, 8));
        jLabel17.setText("*");

        jLabel18.setForeground(new java.awt.Color(247, 8, 8));
        jLabel18.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(header3)
                .addGap(112, 112, 112)
                .addComponent(wellbl, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNamelbl)
                            .addComponent(DOBlbl)
                            .addComponent(phNolbl)
                            .addComponent(Addresslbl)
                            .addComponent(citylbl)
                            .addComponent(pinCodelbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(emaillbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(countrylbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(panNolbl)
                            .addComponent(submitBt, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panNotxt)
                            .addComponent(pinCodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countrytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(citytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phNotxt)
                            .addComponent(userNametxt)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOBtxt)
                            .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backBt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(errlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(header3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wellbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namelbl)
                    .addComponent(nametxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(userNamelbl)
                                    .addComponent(userNametxt))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DOBtxt)
                                    .addComponent(DOBlbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phNolbl)
                                    .addComponent(phNotxt))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Addresslbl)
                                    .addComponent(jLabel18)))
                            .addComponent(addresstxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(citylbl)
                            .addComponent(jLabel15)))
                    .addComponent(citytxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinCodelbl)
                    .addComponent(pinCodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countrylbl)
                    .addComponent(countrytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panNolbl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panNotxt)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emaillbl))))
                .addGap(18, 18, 18)
                .addComponent(errlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBt)
                    .addComponent(backBt))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtActionPerformed
        CustomerServiceMenu obj = new CustomerServiceMenu();
        
        obj.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_backBtActionPerformed

    private void addresstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addresstxtActionPerformed

    private void submitBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtActionPerformed
            String address=addresstxt.getText();
            String city=citytxt.getText();
            String pinCode=pinCodetxt.getText();
            String country=countrytxt.getText();
            String email=emailtxt.getText();
            try
            {
            update5(address,city,pinCode,country,email);}
            catch(SQLException | ClassNotFoundException e)
            {
                System.out.println("sub");
               
            }
           
    }//GEN-LAST:event_submitBtActionPerformed

    /**
     * @param args the command line arguments
     */
    private void update5(String adr,String city,String pincode,String country,String email)throws SQLException,ClassNotFoundException
    {
       
        Connection con = ConnectionClass.getConnected();
        Statement s =con.createStatement();
        
        //System.out.println("Entered");
    String query="update customer set address='"+adr+"',city='"+city+"',pin='"+pincode+"',country='"+country+"',email_id='"+email+"' where customer_id="+id;
    
    int r= s.executeUpdate(query);
      
    if(r>0) errlbl.setText("update Successfull");
    }
    public static void main(String args[])throws SQLException,ClassNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Addresslbl;
    private javax.swing.JLabel DOBlbl;
    private javax.swing.JLabel DOBtxt;
    private javax.swing.JTextField addresstxt;
    private javax.swing.JButton backBt;
    private javax.swing.JLabel citylbl;
    private javax.swing.JTextField citytxt;
    private javax.swing.JLabel countrylbl;
    private javax.swing.JTextField countrytxt;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel errlbl;
    private javax.swing.JLabel header3;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel namelbl;
    private javax.swing.JLabel nametxt;
    private javax.swing.JLabel panNolbl;
    private javax.swing.JLabel panNotxt;
    private javax.swing.JLabel phNolbl;
    private javax.swing.JLabel phNotxt;
    private javax.swing.JLabel pinCodelbl;
    private javax.swing.JTextField pinCodetxt;
    private javax.swing.JButton submitBt;
    private javax.swing.JLabel userNamelbl;
    private javax.swing.JLabel userNametxt;
    private javax.swing.JLabel wellbl;
    // End of variables declaration//GEN-END:variables
}
